####################################
# 15-112 Term Project
# Name: Sunny Liang
# This game is based on the original Double Panda game: 
# https://www.coolmathgames.com/0-double-panda
####################################

####################################
# This file contains:
#   Platform class
#   Bamboo class
#   Candy class
# Each class contains properties of the object and may contain images.
# All of these are generated by the main app during runtime.
####################################

import math, random, copy, time
from characters import *
# following framework from cmu_112_graphics
from cmu_112_graphics import *

# platforms to stand on in addition to the floor
class Platform(object):
    levelHeight = Player.scaledHeight + 15
    minLength = 125
    maxLength = 450

    def __init__(self, level, x0, x1, app):
        self.level = level # max level is 5
        self.height = self.level * Platform.levelHeight
        self.x0 = x0
        self.x1 = x1
        self.enemiesOn = []
    
    def getImage(self, app):
        pass

    def addEnemy(self, enemy):
        self.enemiesOn.append(enemy)

    def __repr__(self):
        return f'Platform\tx0: {self.x0}\tx1: {self.x1}\tlevel: {self.level}' + f'\t\tenemies: {self.enemiesOn}'

# red panda can climb bamboo
class Bamboo(object):
    width = 30

    def __init__(self, x, startingHeight, app):
        self.x = x
        self.startingHeight = startingHeight
        # image = 
    
    def __repr__(self):
        return f'Bamboo\tx: {self.x}'

# candy gives players points
class Candy(object):
    # Candy types: cupcake, pie slice, fortune cookie, fried rice
    standardWidth = 40

    def __init__(self, x, y, app):
        self.app = app
        self.x = x
        self.y = y
        self.getCandyTypeAndScoreGain()
    
    def getCandyTypeAndScoreGain(self):
        r = random.randint(0, 100)
        if (r < 70):
            self.candyType = 'Cupcake'
            self.scoreGain = 50
            # following picture captured from: https://www.coolmathgames.com/0-double-panda
            self.image = self.app.loadImage('cupcake.png')
            self.width, self.height = self.image.size
        elif (70 < r < 98):
            self.candyType = 'Pie Slice'
            self.scoreGain = 100
            # following picture captured from: https://www.coolmathgames.com/0-double-panda
            self.image = self.app.loadImage('cupcake.png')
            self.width, self.height = self.image.size
        else:
            self.candyType = 'Fortune Cookie'
            self.scoreGain = 500
            # following picture captured from: https://www.coolmathgames.com/0-double-panda
            self.image = self.app.loadImage('cupcake.png')
            self.width, self.height = self.image.size
    
    def makeIntoFriedRice(self):
        self.candyType = 'Fried Rice'
        self.scoreGain = 1000
        # following picture captured from: https://www.coolmathgames.com/0-double-panda
        self.image = self.app.loadImage('friedrice.png')
        self.width, self.height = self.image.size